name: 'Extract ipynb to python scripts'
description: 'Extracts ipython notebooks into script files with the same name but a .py extension'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        cache: 'pip'
    - name: install python deps via pip
      run: pip install jupyter ipykernel
      shell: bash
    - name: find ipynb files and convert to .py
      run: find . -name '*.ipynb' -not -path './lib/*' -exec jupyter nbconvert --to script {} \;
      shell: bash
