name: 'Extract ipynb to python scripts'
description: 'Extracts ipython notebooks into script files with the same name but a .py extension'
runs:
  steps:
    - uses: actions/setup-python@v5
      with:
        cache: 'pip'
    - run: pip3 install jupyter ipykernel
    - run: find . -name '*.ipynb' -not -path './lib/*' -exec jupyter nbconvert --to script {} \;
